# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='rotation_period',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
