# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171025_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_water',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
