# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171025_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
